<?php
get_template_part('custom_plugins/load_scripts');
get_template_part('custom_plugins/upload_logo');
get_template_part('custom_plugins/nav_menu');
get_template_part('custom_plugins/head');
get_template_part('custom_plugins/documents/index');
get_template_part('custom_plugins/add_post_type_projects');
get_template_part('custom_plugins/display_another_posts');
get_template_part('custom_plugins/display_additional_tape');
get_template_part('custom_plugins/partners/add_post_type');
get_template_part('custom_plugins/support');
get_template_part('custom_plugins/projects/index');
get_template_part('custom_plugins/theme_options/theme_options_main');
get_template_part('custom_plugins/main_page_options/main_page_options_main');
get_template_part('custom_plugins/paginate');
get_template_part('custom_plugins/print_component');
